export const browserCoreExamples = [
  "openabg browser status",
  "openabg browser start",
  "openabg browser stop",
  "openabg browser tabs",
  "openabg browser open https://example.com",
  "openabg browser focus abcd1234",
  "openabg browser close abcd1234",
  "openabg browser screenshot",
  "openabg browser screenshot --full-page",
  "openabg browser screenshot --ref 12",
  "openabg browser snapshot",
  "openabg browser snapshot --format aria --limit 200",
  "openabg browser snapshot --efficient",
  "openabg browser snapshot --labels",
];

export const browserActionExamples = [
  "openabg browser navigate https://example.com",
  "openabg browser resize 1280 720",
  "openabg browser click 12 --double",
  'openabg browser type 23 "hello" --submit',
  "openabg browser press Enter",
  "openabg browser hover 44",
  "openabg browser drag 10 11",
  "openabg browser select 9 OptionA OptionB",
  "openabg browser upload /tmp/file.pdf",
  'openabg browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openabg browser dialog --accept",
  'openabg browser wait --text "Done"',
  "openabg browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openabg browser console --level error",
  "openabg browser pdf",
];
